# Generated by Django 3.1.7 on 2021-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211025_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='Slider/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
