# Generated by Django 3.1.7 on 2021-10-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_slider_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider_Image',
            new_name='SliderImage',
        ),
    ]
