# Generated by Django 3.1.7 on 2021-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211026_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='product_picture/default.png', upload_to='category/'),
        ),
    ]
